### PR TITLE
refactor: Cleanup the project

### PR DESCRIPTION
**Pull request by monsieurnebo**
## Dependencies
- Remove `map-obj` dependency in favor of native `Object.entries` feature
  - See https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Object/entries
- Replace `camelcase` by more trustable `lodash.camelcase`

## Core
- Use new JS standards
- Make things more readable

### CODE REVIEW

**Comment by rafaelxavier-medicalbox** [comment]
Thank you for your PR, I appreciate pro-active work like yours, but I am not fully clear why the change is needed. More details below.

> Remove `map-obj` dependency in favor of native `Object.entries` feature
>
> - See https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Object/entries

map-obj uses `Object.entries` under the hoods. It's convenient to use it instead of rewritting it here...

> Replace `camelcase` by more trustable `lodash.camelcase`

`camelcase` is written by an exceptional dev (sindresorhus) and its unit tests are insanely good [camelcase tests](https://github.com/sindresorhus/camelcase/blob/main/test.js) vs [lodash.camelcase tests](https://github.com/lodash/lodash/blob/master/test/camelCase.test.js).

**Comment by rxaviers** [comment]
Thank you for your PR, I appreciate pro-active work like yours, but I am not fully clear why the change is needed. More details below.

> Remove `map-obj` dependency in favor of native `Object.entries` feature
>
> - See https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Object/entries

map-obj uses `Object.entries` under the hoods. It's convenient to use it instead of rewritting it here...

> Replace `camelcase` by more trustable `lodash.camelcase`

`camelcase` is written by an exceptional dev (sindresorhus) and its unit tests are insanely good [camelcase tests](https://github.com/sindresorhus/camelcase/blob/main/test.js) vs [lodash.camelcase tests](https://github.com/lodash/lodash/blob/master/test/camelCase.test.js).

**Comment by rxaviers** [comment]
Closing due to lack of activity. I am happy to revisit

**Comment by monsieurnebo** [comment]
Hi @rxaviers , 

I missed your answer, sorry.


> map-obj uses `Object.entries` under the hoods. It's convenient to use it instead of rewritting it here...

One more reason not to use a dependency to wrap such as basic & native functionality 🤔 


>  `camelcase` is written by an exceptional dev (sindresorhus) and its unit tests are insanely good [camelcase tests](https://github.com/sindresorhus/camelcase/blob/main/test.js) vs [lodash.camelcase tests](https://github.com/lodash/lodash/blob/master/test/camelCase.test.js).

My bad :)

**Pull request closed without merging**
